# Generated by Django 5.0.6 on 2024-07-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("created_at",),
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
